name: Daily Generate and Publish

on:
  schedule:
    - cron: '58 22 * * *' # 22:58 UTC = 23:58 CET / 00:58 CEST
  workflow_dispatch:

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Run generate script
        run: bun run generate
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
